# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: check-executables-have-shebangs
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.4
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      files: ^.*\.(py|c|h|md|rst|yml)$
- repo: git@github.com:omelet-ai/precommit-jira-message
  rev: v1.0.6
  hooks:
    - id: jira-commit-msg
      stages: [commit-msg]

- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: sh -c "pytest -c setup.cfg"
    language: python
    types: [python]
    pass_filenames: false
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
