name: lint and test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install uv
      run: pip install uv

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install python packages
      run: uv sync --all-groups --frozen

    - name: Cache pre-commit
      uses: actions/cache@v4
      id: cache-pre-commit
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install pre-commit
      if: steps.cache-pre-commit.outputs.cache-hit != 'true'
      run: uv run pre-commit install --install-hooks

    - name: Run pre-commit
      run: uv run pre-commit run --all-files
